version: "3.9"
services:
  stms-patcher:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile


  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - "stms-patcher"
    depends_on:
      - "stms-patcher"
    ports:
      - "7776:443"
