FROM nginx:alpine
EXPOSE 7776
RUN rm /etc/nginx/conf.d/default.conf
COPY cer/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./cer/keys.key /etc/ssl/auth-proxy/keys.key
COPY ./cer/bundle.crt /etc/ssl/auth-proxy/bundles.crt
